### ISSUE TITLE
New problem in 1.0.0.2 - Error log: Not all of mandatory fields are set for creating of an OrderItem object

### ISSUE THREAD

**Issue by Sirdcryot** [PaysonAB/Payson-Checkout2-Prestashop#3]
Hi, 

I installed version 1.0.0.0 last week and managed to conduct payments in production mode (Prestashop 1.6.1.4) with some minor adjustment. Today I installed version 1.0.0.2 and is no longer able to get pass the checkout. The error log states "Not all of mandatory fields are set for creating of an OrderItem object". When I compared the database between version 1.0.0.0 and version 1.0.0.2 there is a new table 'ps_payson_embedded_order". I using the guest checkout in prestashop. Any ideas what happend between the two versions??

**Comment by PaysonAB** [comment]
Please check that you submit all the required parameters for each product. You can find more information in the following link.

https://api.payson.se/wp/order-item/

**Comment by PaysonAB** [comment]
Hi, 

In the version 1.0.0.1 we implemented an larger commit to update our libary. This introduced new stricter validations on the order items that are include in each order. However a few of these validtions were too strict and tax rate and unit price has been changed to allow them to be set to value 0(zero). Please update to latest version, 1.0.0.4, to see if the issue has been solved. If the issue still persists, Please contact us again at our homepage: https://www.payson.se/myaccount/contact/contact# and provide us with your Payson account. We can then investigate your transactions to see what could be wrong.

Best regards
Payson integration
